### ISSUE TITLE
views.py DetailView

### ISSUE THREAD

**Issue by pilks7** [mdn/django-locallibrary-tutorial#10]
Spent the longest time on this, I had to specifically import Detail View like so
`from django.views.generic.detail import DetailView`

`from django.views import generic`

 doesn't seem to work, throwing this:

```
 class BookDetailView(DetailView):
NameError: name 'DetailView' is not defined
```

I'm using python 3.6 and django 2.02 (on ubuntu 16.04)

**Comment by hamishwillee** [comment]
Are you saying that you imported the requirements.txt into your environment and built this project as-is from github and it didn't work?

**Comment by pilks7** [comment]
No that's not what I'm saying. Just saying I followed the tutorial exactly
up to this point and it wouldn't work, even when I copy/pasted the views.py
verbatim. I had to use the specific import, that's all

**Comment by hamishwillee** [comment]
Many apologies. I completely forgot about this.

The documentation does correctly show how to do this:
```python
from django.views import generic

class BookDetailView(generic.DetailView):
    model = Book
```
As you see, the Detail view is in `django.views.generic`, not in `django.views.generic.detail`
