### ISSUE TITLE
How to enable CORS headers in locallibrary tutorial ?

### ISSUE THREAD

**Issue by tbiat** [mdn/django-locallibrary-tutorial#107]
Hello,
Thanks for providing this tutorial, helping a lot. I'm trying to enable CORS headers (I followed the https://www.stackhawk.com/blog/django-cors-guide/ ) mainly changing the settings.py file : 
INSTALLED_APPS = [
...
'corsheaders',
...
]
MIDDLEWARE = [
...,
'corsheaders.middleware.CorsMiddleware',
'django.middleware.common.CommonMiddleware',
...,
]
CORS_ALLOW_ALL_ORIGINS = True

But the response still doesn't include CORS. It seems that whatever I do regarding corsheaders in settings.py, it is overridden by something else . 

Thanks in advance for the response !

**Comment by mohammedyousuf051** [comment]
Did you install corsHeaders if not do run this command in your app 
>> pip install django-cors-headers
this enables the cors in your django app

**Comment by tbiat** [comment]
> Did you install corsHeaders if not do run this command in your app
> 
> > > pip install django-cors-headers
> > > this enables the cors in your django app

Yes I did. Changing of the config for other middlewares works (referrer policy for instance with the security middleware package), but CORS config looks like not taken into account.

**Comment by hamishwillee** [comment]
> This is a bit out of scope for the tutorial. Closing.

Sorry, I see you are confused. Basically the tutorial covers a number of things, but cross origin sharing is not one of them. This area is for bugs around the tutorial not for support on doing something not covered by the tutorial.
