### ISSUE TITLE
Visual Studio Code debugging

### ISSUE THREAD

**Issue by eddhyne** [mdn/django-locallibrary-tutorial#125]
### Before submitting the issue, confirm that you've checked everything in the following list, and mark them as completed here:

- [X] Issue is reproducible on this repository by following the [quick-start instructions](https://github.com/mdn/django-locallibrary-tutorial#quick-start).
- [X] A clean/fresh database was used when the issue was encountered.
- [X] Information about the environment setup when the issue was encountered is included in the issue.
- [X] Output logs are included in the issue.

### What was incorrect, unhelpful, or unexpected?

I can't get VSCODE debugger to stop at any of my breakpoints in my templates/*.html
my launch.json file is:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Django",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}\\django_projects\\manage.py",
            "args": [
                "runserver"
            ],
            "django": true,
            "justMyCode": false,
            "host": "localhost"
        }
    ]
}
 

### What did you expect to see?

A stop in execution at my breakpoint

**Comment by caugner** [comment]
> I can't get VSCODE debugger to stop at any of my breakpoints in my templates/*.html

Hi @eddhyne, 👋 

I don't think it is possible at all to stop at breakpoints in templates, unfortunately. These templates are not executed line by line, but rather parsed as a whole by the templating engine.

If you need to debug a template, you might be able to use the [`{% debug %}`](https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#debug) template tag. Hope that helps! 🤞

**Comment by eddhyne** [comment]
Not happy to hear that but thanks very much for looking into it.

Ed Dhyne
Direct: 954-608-6603
***@***.******@***.***>
www.linkedin.com
