### ISSUE TITLE
Copy skeleton into a new project

### ISSUE THREAD

**Issue by eddhyne** [mdn/django-locallibrary-tutorial#126]
### Before submitting the issue, confirm that you've checked everything in the following list, and mark them as completed here:

- [X] Issue is reproducible on this repository by following the [quick-start instructions](https://github.com/mdn/django-locallibrary-tutorial#quick-start).
- [X] A clean/fresh database was used when the issue was encountered.
- [X] Information about the environment setup when the issue was encountered is included in the issue.
- [X] Output logs are included in the issue.

### What was incorrect, unhelpful, or unexpected?

How do I copy the Django/skeleton_website into a new project? I am a beginner so please give me step-by-step instructions.

### What did you expect to see?

Step-by-step instructions on how to  copy the Django/skeleton_website into a new project

**Comment by hamishwillee** [comment]
YOu don't need to copy it. Just follow the first part of the tutorial and create a new one. https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website

**Comment by eddhyne** [comment]
Thanks.

Ed Dhyne
Direct: 954-608-6603
***@***.******@***.***>
www.linkedin.com
