### ISSUE TITLE
test_renew_form_date_max test failure

### ISSUE THREAD

**Issue by blackhatrob** [mdn/django-locallibrary-tutorial#14]
Form validation (from catalog/forms.py) uses datetime in all cases to generate the date.
```
def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        
        #Check date is not in past. 
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
        #Check date is in range librarian allowed to change (+4 weeks)
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data
```

The test function test_renew_form_date_max() uses timezone.now() and a datetime.timedelta() to create the date to bind to the form for validation. Is this breaking the test since timezone.now() uses UTC?

```
def test_renew_form_date_max(self):
        """
        Test form is valid if renewal_date is within 4 weeks
        """
        date = timezone.now() + datetime.timedelta(weeks=4)
        form_data = {'renewal_date': date}
        form = RenewBookForm(data=form_data)
        self.assertTrue(form.is_valid())
```

**Comment by sbhaseen** [comment]
Was having this same issue, where the unit tests all worked in the morning but broke when I looked at them again in the evening despite not touching the `test_forms.py` code. A fix that worked for me was changing `TIMEZONE = ...` in my `settings.py` file from my local  of `'America/Eastern'` to `'UTC'`.

**Comment by hamishwillee** [comment]
This is now fixed: https://github.com/mdn/django-locallibrary-tutorial/commit/5bc3bc175f924769380281648308db1a13cabb90. The tutorial was correct but the example was incorrect.

As you noted, the use of date = timezone.now() could result in a time that was outside of 4 weeks under some circumstances.
