### ISSUE TITLE
Create/Update/Delete author

### ISSUE THREAD

**Issue by nameisnot** [mdn/django-locallibrary-tutorial#17]
Sorry to have to say this but not able to hooking the "update" and "delete" pages to the side bar. 

Tried putting the url mapping like:

    <a href="{% url 'author_update' author.pk %}">Update Author</a> 
in the base template but since then coming up with error:

    Reverse for 'author_update' with arguments '('',)' not found

Will somebody please let me know where I going wrong.

**Comment by chrisdavidmills** [comment]
@hamishwillee can you please take a look at this when you get a spare moment?

**Comment by hamishwillee** [comment]
@nameisnot Have you defined an URL pattern with the appropriate name (ie 'author_update')? The reverse function needs to be able to have some way of working out what pattern it is supposed to revers. See https://github.com/mdn/django-locallibrary-tutorial/blob/master/catalog/urls.py#L37

**Comment by hamishwillee** [comment]
Closing, as my answer above is sufficient (correct) and the poster has not responded.
