### ISSUE TITLE
Authentication views

### ISSUE THREAD

**Issue by rahulblhra** [mdn/django-locallibrary-tutorial#19]
ERRORS:
?: (urls.E004) Your URL pattern [<URLResolver <URLPattern list> (admin:admin) 'admin/'>, <URLResolver <module 'catalog.urls' from 'C:\\Users\\Rahul\\Documents\\locallibrary\\catalog\\urls.py'> (None:None) 'catalog/'>, <URLPattern ''>, <URLPattern '^static/(?P<path>.*)$'>] is invalid. Ensure that urlpatterns is a list of path() and/or re_path() instances.

System check identified 1 issue (0 silenced).
 **allthe code matches still shows an error please help**

**Comment by hamishwillee** [comment]
Have you got your failing version on github anywhere?

**Comment by hamishwillee** [comment]
I am closing this. Not enough information to debug. Though it is almost certainly the case that you have not declared your urls correctly.
