### ISSUE TITLE
tutorial part 9 generic editing page layout different from example

### ISSUE THREAD

**Issue by EliseRemise** [mdn/django-locallibrary-tutorial#21]
The examples shown in tutorial part 9 generic editing templates renders different with the code examples as shown in the tutorial. This might be confusing to novices like me. form.as_table returns the form wrapped in `<tr>` tags but this needs to be wrapped in an `<table>` tag for it to be displayed as a table as shown  as example. There are no `<table>`  tags in the example code.

**Comment by hamishwillee** [comment]
Thanks very much. This is now fixed to match in both MDN and this example!
