### ISSUE TITLE
Missing table tags

### ISSUE THREAD

**Issue by ahwebd** [mdn/django-locallibrary-tutorial#24]
First, big thanks for this great tutorial.

In https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms#The_template
and as per [django docs](https://docs.djangoproject.com/en/2.0/topics/forms/#form-rendering-options) we still need to provide the `<table>` tag even if we use `form.as_table`
```html
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit">
  </form>
```
should be:
```html
  <form action="" method="post">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <input type="submit" value="Submit">
  </form>
```
(was trying with django 1.11 and table was not rendered without the `<table>` tag)

**Comment by hamishwillee** [comment]
This is probably correct/better - but fwiw the tutorial does work with Django 2.0/recent versions.

**Comment by ahwebd** [comment]
The django docs link above is for django 2.0, and still requires that we need to provide the `<table>` tag

**Comment by ahwebd** [comment]
and just to confirm, tried now with django 2.0, still table not rendered if `<table>` tag is not provided

**Comment by ahwebd** [comment]
source code:
https://github.com/django/django/blob/master/django/forms/forms.py#L277

```python
    def as_table(self):
        "Return this form rendered as HTML <tr>s -- excluding the <table></table>."
        return self._html_output(
            normal_row='<tr%(html_class_attr)s><th>%(label)s</th><td>%(errors)s%(field)s%(help_text)s</td></tr>',
            error_row='<tr><td colspan="2">%s</td></tr>',
            row_ender='</td></tr>',
            help_text_html='<br><span class="helptext">%s</span>',
            errors_on_separate_row=False,
)
```

**Comment by hamishwillee** [comment]
Thanks @ahwebd . I hope to go through and do some fixes (including reviewing this) in the coming months. Appreciate you taking the time to post this.

**Comment by hamishwillee** [comment]
Thanks very much. This is now fixed. You're quite right about this.
