### ISSUE TITLE
Tutorial 8: no such column: catalog_bookinstance.borrower_id 

### ISSUE THREAD

**Issue by unlikenesses** [mdn/django-locallibrary-tutorial#28]
**Django:** 2.1.2
**Python:** 3.7.0

When I get to [the "Loan a Few Books" section](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication#Loan_a_few_books) of Tutorial 8, and go to a book detail view in the admin, I get this error:

> OperationalError at /admin/catalog/bookinstance/
no such column: catalog_bookinstance.borrower_id

**Comment by unlikenesses** [comment]
Seemed to be fixed by stopping the server, removing the `borrower` migration, re-adding it and migrating, then re-starting the server.

**Comment by hamishwillee** [comment]
Thanks. Sounds like a problem with the migration. Probably an aberration (ie something that I can't reproduce, so I am going to assume is and oddity with the toolchain that won't happen again or is outside control of this project.)
