### ISSUE TITLE
Language Class

### ISSUE THREAD

**Issue by vbroskas** [mdn/django-locallibrary-tutorial#3]
First off, this is more of a question, not so much an issue, so if there is somewhere else I should be asking please feel free to delete this and re-direct me.

For the association of Language and Book, I understand that a book can be written in multiple languages, so it makes sense to have the foreign key from Language to Book (many books in many languages). However, wouldn't we also want to know what language a particular instance of a book is written in? I'm just confused as to why there is no relationship between Language and BookInstance, or is the fact that we have a foreign key between Book and BookInstance enough to tie in the language of a particular book?

Thanks for any help you can provide!

**Comment by chrisdavidmills** [comment]
I think this is one of those instances that can be handled with a reverse lookup. This is explained in https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views#Creating_the_Detail_View_template

**Comment by hamishwillee** [comment]
Yes, that's right. On that page the Chris references it is this bit:
```
This method is needed because you declare a ForeignKey (one-to many)
field in only the "one" side of the relationship. 
Since you don't do anything to declare the relationship in the other
 ("many") model, it doesn't have any field to get the set of associated 
records. To overcome this problem, Django constructs an appropriately named 
"reverse lookup" function that you can use. 
The name of the function is constructed by lower-casing the model name 
where the ForeignKey was declared, followed by _set (i.e. so the function created in Book is bookinstance_set()).
```
