### ISSUE TITLE
Outdated dependencies (whitenoise & psycopg2)

### ISSUE THREAD

**Issue by Matthew-J-Billings** [mdn/django-locallibrary-tutorial#30]
Hi - deploying this to Heroku fails due to a breaking change in the latest version of Whitenoise (http://whitenoise.evans.io/en/stable/changelog.html#v4-0)

Removing any reference to whitenoise in wsgi.py seems to resolve it.

There's also a breaking change on deployment with psycopg2.  Buried in the Heroku logs is the advice to now use `pip install psycopg2-binary` rather than `pip install psycopg2`  - this seems to resolve the issue

Edit: as far as I can tell replacing psycopg2 with psycopg2-binary also leads to a failed build,
Leaving them both in seems to prevent the database from being properly created on the server (runtime error `relation catalog_book does not exist` - this is the first time the app tries to get something from the db).  It works ok locally (using sqlite.db).

**Comment by hamishwillee** [comment]
Thanks very much @Matthew-J-Billings .

I'm currently updating the docs. I will be looking at deployment again in the coming 2 weeks so this will be very useful.

**Comment by hamishwillee** [comment]
@Matthew-J-Billings 
Just FYI, I still haven't updated whitenoise, but updating to  `psycopg2-binary` rather than `psycopg2` allowed `git push heroku master` to succeed (it failed with a "module not found" previously). The build worked fine from the website.

**Comment by hamishwillee** [comment]
I've updated the example to latest of everything, and it all uploads and works. I am therefore closing. Thanks for this - it was very helpful.
