### ISSUE TITLE
mismatch of UML design and actual code

### ISSUE THREAD

**Issue by lokesh1729** [mdn/django-locallibrary-tutorial#34]
Hey,

I see in UML that relationship between `Book` and `Author` is `ManyToMany` but whereas in code `catalog/models.py` (quoting the code below) it was mentioned that "book can only have one author"

> author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in file.

Why there is discrepancy ???

**Comment by hamishwillee** [comment]
Because the design changed during implementation without corresponding update to the docs.  Fix on mdn and in example now. Thanks for spotting this.
