### ISSUE TITLE
Not following PEP8 Rules

### ISSUE THREAD

**Issue by lokesh1729** [mdn/django-locallibrary-tutorial#35]
Hi,

It's disheartening to see projects from `mdn` doesn't follow `PEP8` rules in writing the  code. Did you ever done a `pylint` and see the results ??

**Comment by hamishwillee** [comment]
No, but we did use a flake8 test. This is slowly evolving to match.

**Comment by hamishwillee** [comment]
I've done a new run of flake8 fixups. There are still some reported errors, but most of these are to do with lines too long and modules being called within the body of files. Now while these are not "in line" with PEP8, they are very much in line with the way the example is designed. 

I am therefore closing this. Happy to take specific fixes as PRs, provided they follow the design of the example.
