### ISSUE TITLE
 date time picker not working

### ISSUE THREAD

**Issue by pradeeshattlee** [mdn/django-locallibrary-tutorial#38]
I tried all possible types but it wont work kindly give me a simple solution to add the date  widget to it 
thanks in advance

**Comment by hamishwillee** [comment]
This is not a defect - the example uses the simplest possible date entry available. If you want something else you can do a search - e.g. https://stackoverflow.com/questions/3367091/whats-the-cleanest-simplest-to-get-running-datepicker-in-django
