### ISSUE TITLE
Problem with "/catalog/models.py"

### ISSUE THREAD

**Issue by jafar95** [mdn/django-locallibrary-tutorial#58]
My Django version: 2.2.5
In line 47: **Instance of 'ManyToManyField' has no 'all' memberpylint(no-member).**
In line 53: **Instance of 'Book' has no 'id' memberpylint(no-member)**
In line 101: **Instance of 'ForeignKey' has no 'title' memberpylint(no-member)**
In line 116: **Instance of 'Author' has no 'id' memberpylint(no-member)**

**Comment by hamishwillee** [comment]
This is an error from pylint against this repository? What can I tell you, it works. And some of the fields are autogenerated from teh framework.

**Comment by jafar95** [comment]
I solved this problem. Seems there was a problem with pyLint.  As per the solution provided here: https://stackoverflow.com/questions/45135263/class-has-no-objects-member , I ran **pip install pylint-django** in my VS code terminal, then in VS code hit **Ctrl+ ,** (comma). Took me to the **User settings**. There I searched **Linting: Pylint Path**. There in input box, I put **"pylint_django"**. That solved everything. (P.S. I am totally beginner in python and django. That was silly, indeed)

**Comment by hamishwillee** [comment]
No worries. Thanks!
