### ISSUE TITLE
Are there plans to update to Django 3

### ISSUE THREAD

**Issue by diek** [mdn/django-locallibrary-tutorial#59]
I love your tutorial, I recommend it a lot in our Django group. I am curious, are there are plans to update the tutorial to Django 3?

I do not think async would be needed, and from what I understand async is still being worked on. This would make updating the tutorial a bit easier imo

**Comment by chrisdavidmills** [comment]
Hi @diek !

We definitely want to update it to Django 3 at some point in the not too distant future, although at the moment we are really swamped and have very little budget. Probably more like the end of this year or start of next year, at this rate.

I guess it also depends on how big a change that would need to be; I've not really looked at Django 3. What are your feelings on that?

**Comment by hamishwillee** [comment]
And also whether volunteers would like to take on some of the work :-).

**Comment by diek** [comment]
Hi @chrisdavidmills and @hamishwillee 
Thanks for getting back to me. The amount of work required depends upon the decision to include async or not. That of course is a Mozilla decision.
2 possible routes
1. Upgrade to Django 3, leaving out async for now, then,
2. Add async when Django 3.2(LTS) is released in the Spring of 2021. Async should be completely ready by then, imo.

This would allow a quicker update to the current tutorial imo.
Yes, I will help. :)

**Comment by hamishwillee** [comment]
Thanks @diek ! My gut feeling is that Mozilla don't have the resource to take care of this now, but it is worth adding a note on the docs saying that we're aware of  Django 3 and hope to update in Django 3.2 timeframes.

Let's see what @chrisdavidmills says.

**Comment by diek** [comment]
If you can live without the async(which I think makes sense until the LTS release next year), I have some time, and I think I could take on an update to Django 3. I am currently helping Danny and Audrey Roy Greenfeld with their upcoming release of "Django Crash Course: Covers Python 3.8 and Django 3.x." (currently in Beta). Let me know.

**Comment by hamishwillee** [comment]
Hi @diek,

This requires and update to the code here, and also to the documentation on MDN. If you are happy to do both of those then that would be brilliant. 

I'm happy to try help with review (as I'm sure will @chrisdavidmills ) though I'm a little overloaded on unrelated work, so likely it would be lagging.

**Comment by diek** [comment]
Ok, I have to clue up my help with Danny and Audrey. I will let you know when I can start 1-2 weeks from now, max.

**Comment by samshum2** [comment]
File "/home/pi/django-locallibrary-tutorial-master/locallibrary/settings.py",            line 133, in <module>
    import dj_database_url
ModuleNotFoundError: No module named 'dj_database_url'

**Comment by hamishwillee** [comment]
The example is now mostly updated to Django 3. Ie it has been updated so that it works, but I have not yet made sure it makes "best use" of Django. Still, closing as this counts :-)
