### ISSUE TITLE
Reference with parentheses

### ISSUE THREAD

**Issue by TrajanAmsterdam** [mdn/django-locallibrary-tutorial#63]
In the https://github.com/mdn/django-locallibrary-tutorial/blob/master/catalog/models.py code, in class Books, you refer to 'Language'. Why use ''? Language as a model is already defined, so shouldn't it be simply Language, so it refers to the model? Same question in class BookInstance, it refers to 'Book' instead of Book. Am I making a wrong assumption here? Thanks in advance for the help!

**Comment by hamishwillee** [comment]
A book has a language associated - ie the book might be in English or French or whatever. If that does not answer your question, I do not understand your point. Could you insert the code that offends you?

**Comment by TrajanAmsterdam** [comment]
```
class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in file.
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn'
                                      '">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    # ManyToManyField used because a genre can contain many books and a Book can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
```

So what I mean: The _field_ language of _class_ Book references the _model_ Language. But it does so with parenthesis: 'Language'. Shouldn't it be without parentheses?

**Comment by hamishwillee** [comment]
So you mean like:
```
language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True)
```
no. Without a key this would be a Language object. ForeignKey takes a string for the type.

**Comment by TrajanAmsterdam** [comment]
Ah ok. Thanks for your explanation!
