### ISSUE TITLE
the form validation for the renewal is not working

### ISSUE THREAD

**Issue by trowa116** [mdn/django-locallibrary-tutorial#69]
i cant seem to get the form to trigger the validation error for dates that are too far in the past or the future. It submits the form as long as the field is a valid date.

**Comment by trowa116** [comment]
it worked when i switched over to the RenewBookModelform

**Comment by hamishwillee** [comment]
Does the validation work for this project (ie the sources defined in this repo) when running the set of dependencies in requirements.txt?

If it does, then the code here works, and you want to delta what your version against this code to work out where you have gone wrong. If not, then there may be something broken in the example.

**Comment by hamishwillee** [comment]
I tested the code in this repo and it works - you can see the form part here: https://github.com/mdn/django-locallibrary-tutorial/blob/master/catalog/forms.py#L8

Anyway, sounds like you got it working so I will close!
