### ISSUE TITLE
SystemCheckError

### ISSUE THREAD

**Issue by nuttaa** [mdn/django-locallibrary-tutorial#72]
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
<class 'catalog.admin.BookAdmin'>: (admin.E108) The value of 'list_display[2]' refers to 'display_genre', which is not a callable, an attribute of 'BookAdmin', or an attribute or method on 'catalog.Book'.
<class 'catalog.admin.BookInstanceAdmin'>: (admin.E108) The value of 'list_display[2]' refers to 'borrower', which is not a callable, an attribute of 'BookInstanceAdmin', or an attribute or method on 'catalog.BookInstance'.

**Comment by hamishwillee** [comment]
Thanks. I plan on looking at Django example again in the next week or so. Assigned to me.

**Comment by hamishwillee** [comment]
@nuttaa Is this your own code, or the code from this repo? Can you reproduce this after following the instructions here: https://github.com/mdn/django-locallibrary-tutorial#quick-start

If so, can you please explain exactly how you got the above error. The admin is rock solid for me.

My guess is that this is for your own code and that BookInstance.borrower is not defined.

**Comment by pwhau** [comment]
Hello @nuttaa I got same ERRORS before when I followed [the Django Tutorial Part 4](https://developer.mozilla.org/zh-TW/docs/Learn/Server-side/Django/Admin_site)

------
The first error we should put below code **(in models.py not admin.py)**

> **class Book(models.Model):**
> .....
> .....
> .....
> def display_genre(self):
> > """Create a string for the Genre. This is required to display genre in Admin."""
> >         return ', '.join(genre.name for genre in self.genre.all()[:3]) 

> display_genre.short_description = 'Genre'

------
The second error is the Tutorial didn't asked for 'borrower' so we could delete the 'borrower' string

If it still can't solve your problems, I apologize.

**Comment by hamishwillee** [comment]
@nuttaa Pwhau is correct. The first error indicates that display_genre is being called but is not defined. The function is mention in the documentation, so I suspect you just missed this line. 

Further for the second problem this is reporting that in [this line](https://github.com/mdn/django-locallibrary-tutorial/blob/master/catalog/admin.py#L65) the "borrower" field is not defined

```
@admin.register(BookInstance)
class BookInstanceAdmin(admin.ModelAdmin):
    ...
    list_display = ('book', 'status', 'borrower', 'due_back', 'id')
```
Basically you need a line like [this](https://github.com/mdn/django-locallibrary-tutorial/blob/master/catalog/models.py#L77) in your model:
```
class BookInstance(models.Model):
    ...
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
```
The need for adding this line is covered in the user authentication section: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication

I think this is resolved. Thanks for your help @pwhau !
