### ISSUE TITLE
Check if create home page correctly redirects to home page

### ISSUE THREAD

**Issue by hamishwillee** [mdn/django-locallibrary-tutorial#8]
From https://discourse.mozilla.org/t/django-local-library-project-creating-your-home-page-issues/24052

website programming section -> django -> Part 5: creating our home page.

At the end of this section you are supposed to load the home page using http://127.0.0.1:8000 and you are supposed to be redirected to http://127.0.0.1:8000/catalog which shows the books library home page. This is not what actually happens. When I load http://127.0.0.1:8000 I get a 404 error. However if I append /catalog then I get the books library home page. So my question is: is the tutorial incorrect or is this the expected behavior?

**Comment by hamishwillee** [comment]
It does!

**Comment by Maujor** [comment]
> It does!

So I suggest:
On Django Tutorial Part 8: User authentication and permissions

`LOGIN_REDIRECT_URL = '/'`

should be:

`LOGIN_REDIRECT_URL = '/catalog/'`
