### ISSUE TITLE
Add fixtures to catalog

### ISSUE THREAD

**Issue by calvh** [mdn/django-locallibrary-tutorial#93]
I suggest adding some mock data into a fixtures folder

https://docs.djangoproject.com/en/3.2/howto/initial-data/

**Comment by hamishwillee** [comment]
@calvh Thanks you. Fixtures certainly look like a useful feature (which I did not know about). But I'm not sure where they'd be useful in the context of this tutorial. Did you have any particular case in mind?

**Comment by calvh** [comment]
I think they'd be useful somewhere around Section 4 where you add data via the admin site. Some people (like me) find it tedious to manually enter data and may want an alternative. It might be worth having two sets of fixtures: 

1. One around section 4 so readers can quickly test out the site
2. Another with the updated models including the `borrower` field introduced in section 8

Am I allowed to work on this or is this project restricted to members only?

**Comment by hamishwillee** [comment]
> Am I allowed to work on this or is this project restricted to members only?

You are absolutely allowed to work on this and that would be much appreciated. I think probably it should be added only in one place, and that should probably be either at the end of, or "below", https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Models (this might require modification of the admin section too).

First, the updates should be made and tested as the demo project would be at the end of the models chapter. My concern here is that the models are not "complete" here (there are "challenges") so we need to be clear that whatever we advise works at that point. Then further we should have an update as a PR to https://github.com/mdn/django-locallibrary-tutorial and to the docs.

Does that make sense?

**Comment by calvh** [comment]
Yes, thank you. I will draft some changes and put them here before I make a PR.

**Comment by hamishwillee** [comment]
No, thank you - I'm looking forward to learning something new :-)

**Comment by hamishwillee** [comment]
Closing as no action taken
