### ISSUE TITLE
NoReverseMatch - Reverse for 'logout' not found.

### ISSUE THREAD

**Issue by jswarp** [mdn/django-locallibrary-tutorial#95]
I get this error (front end only, back end works fine):

NoReverseMatch at /catalog/
Reverse for 'logout' not found. 'logout' is not a valid view function or pattern name.
Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/catalog/
Django Version: 	3.1.2
Exception Type: 	NoReverseMatch
Exception Value: 	Reverse for 'logout' not found. 'logout' is not a valid view function or pattern name.

Completely new install. 
Django 3.1.2
Python 3.9.7

**Comment by hamishwillee** [comment]
Thanks for posting. This works on this project if you run the instructions here: https://github.com/mdn/django-locallibrary-tutorial#quick-start

It is correct that there won't be a reverse match at catalog - the reverse match is somewhere under /accounts/logout/.

These are setup in section 8: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication#project_urls

You can see the line here: https://github.com/mdn/django-locallibrary-tutorial/blob/master/locallibrary/urls.py#L49

**Comment by ducktapeonmydesk** [comment]
Make sure your line in base_generic.html has the `?next={{request.path}}` in it.

`<li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>`

**Comment by hamishwillee** [comment]
That's a nice-to-have because it takes you back to the same page. But you'll probably get the same error without that - it is the `{% url 'logout'%}` that is doing the reverse lookup.
